# Prod Overrides
global:
  imageTag: v1.1.2 # Or latest for prod

backendDefaults:
  replicas: 2
  storageSize: 5Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 32Mi

frontend:
  replicas: 2
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m

# Service-Specific Tag Overrides
services:
  user:
    imageTag: v1.1.2
  item:
    imageTag: v1.1.2
  inventory:
    imageTag: v1.1.2
  booking:
    imageTag: v1.1.2
  payment:
    imageTag: v1.1.2
  review:
    imageTag: v1.1.2
  notification:
    imageTag: v1.1.2
